const ENCHANTMENTS = [
  {
    id: 0,
    name: "aqua_affinity",
    displayName: "Aqua Affinity",
    weight: 2,
    maxLevel: 1,
    description: "Speeds up how fast you can mine blocks underwater",
    descriptionTW: "加快在水下挖掘方塊的速度",
  },
  {
    id: 1,
    name: "bane_of_arthropods",
    displayName: "Bane of Arthropods",
    weight: 5,
    maxLevel: 5,
    description: "Increases attack damage against arthropods",
    descriptionTW: "增加對節肢動物的攻擊傷害",
  },
  {
    id: 2,
    name: "binding_curse",
    displayName: "Curse of Binding",
    weight: 1,
    maxLevel: 1,
    description: "Cursed item cannot be removed from player",
    descriptionTW: "被詛咒的物品無法從玩家身上移除",
  },
  {
    id: 3,
    name: "blast_protection",
    displayName: "Blast Protection",
    weight: 2,
    maxLevel: 4,
    description: "Reduces blast and explosion damage",
    descriptionTW: "減少爆炸和爆炸傷害",
  },
  {
    id: 4,
    name: "breach",
    displayName: "Breach",
    weight: 2,
    maxLevel: 4,
    description: "Reduces the effectiveness of a target's armor",
    descriptionTW: "減少目標護甲值的有效性",
  },
  {
    id: 5,
    name: "channeling",
    displayName: "Channeling",
    weight: 1,
    maxLevel: 1,
    description:
      "Summons a lightning bolt at a targeted mob when enchanted item is thrown (targeted mob must be standing in rain)",
    descriptionTW:
      "當附魔物品被投擲時，被擊中的生物會召喚閃電（目標生物必須在雨中）",
  },
  {
    id: 6,
    name: "density",
    displayName: "Density",
    weight: 5,
    maxLevel: 1,
    description: "Increases the damage dealt per fallen block",
    descriptionTW: "根據掉落的方塊距離，增加造成的傷害",
  },
  {
    id: 7,
    name: "depth_strider",
    displayName: "Depth Strider",
    weight: 2,
    maxLevel: 3,
    description: "Speeds up how fast you can move underwater",
    descriptionTW: "加快在水下移動的速度",
  },
  {
    id: 8,
    name: "efficiency",
    displayName: "Efficiency",
    weight: 10,
    maxLevel: 5,
    description: "Increases how fast you can mine",
    descriptionTW: "提高挖掘的速度",
  },
  {
    id: 9,
    name: "feather_falling",
    displayName: "Feather Falling",
    weight: 5,
    maxLevel: 4,
    description: "Reduces fall and teleportation damage",
    descriptionTW: "減少墜落和傳送造成的傷害",
  },
  {
    id: 10,
    name: "fire_aspect",
    displayName: "Fire Aspect",
    weight: 2,
    maxLevel: 2,
    description: "Sets target on fire",
    descriptionTW: "使目標著火",
  },
  {
    id: 11,
    name: "fire_protection",
    displayName: "Fire Protection",
    weight: 5,
    maxLevel: 4,
    description: "Reduces damage caused by fire and lava",
    descriptionTW: "減少火焰和岩漿造成的傷害",
  },
  {
    id: 12,
    name: "flame",
    displayName: "Flame",
    weight: 2,
    maxLevel: 1,
    description: "Turns arrows into flaming arrows",
    descriptionTW: "將箭矢轉換為火焰箭矢",
  },
  {
    id: 13,
    name: "fortune",
    displayName: "Fortune",
    weight: 2,
    maxLevel: 3,
    description: "Increases block drops from mining",
    descriptionTW: "增加挖掘方塊的掉落戰利品數量",
  },
  {
    id: 14,
    name: "frost_walker",
    displayName: "Frost Walker",
    weight: 2,
    maxLevel: 2,
    description:
      "Freezes water into ice so that you can walk on it (and also allows you to walk on magma blocks without taking damage)",
    descriptionTW: "將水凍結成冰以便行走（同時可以在熔岩方塊上行走而不受傷）",
  },
  {
    id: 15,
    name: "impaling",
    displayName: "Impaling",
    weight: 2,
    maxLevel: 5,
    description: "Increases attack damage against sea creatures",
    descriptionTW: "增加對海洋生物的攻擊傷害",
  },
  {
    id: 16,
    name: "infinity",
    displayName: "Infinity",
    weight: 1,
    maxLevel: 1,
    description: "Shoots an infinite amount of arrows",
    descriptionTW: "無限使用箭矢不消耗數量",
  },
  {
    id: 17,
    name: "knockback",
    displayName: "Knockback",
    weight: 5,
    maxLevel: 2,
    description: "Increases knockback dealt (enemies repel backwards)",
    descriptionTW: "增加近戰擊退效果（敵人向後推）",
  },
  {
    id: 18,
    name: "looting",
    displayName: "Looting",
    weight: 2,
    maxLevel: 3,
    description: "Increases amount of loot dropped when mob is killed",
    descriptionTW: "增加擊殺生物時掉落的戰利品數量",
  },
  {
    id: 19,
    name: "loyalty",
    displayName: "Loyalty",
    weight: 5,
    maxLevel: 3,
    description: "Returns your weapon when it is thrown like a spear",
    descriptionTW: "將你的武器在像矛一樣被投擲後返回",
  },
  {
    id: 20,
    name: "luck_of_the_sea",
    displayName: "Luck of the Sea",
    weight: 2,
    maxLevel: 3,
    description: "Increases chances of catching valuable items",
    descriptionTW: "增加釣到珍貴物品的機率",
  },
  {
    id: 21,
    name: "lure",
    displayName: "Lure",
    weight: 2,
    maxLevel: 2,
    description: "Increases the rate of fish biting your hook",
    descriptionTW: "增加魚咬鉤的速度",
  },
  {
    id: 22,
    name: "mending",
    displayName: "Mending",
    weight: 2,
    maxLevel: 1,
    description: "Uses XP to mend your tools, weapons, and armor",
    descriptionTW: "使用經驗值修復你的工具、武器和盔甲",
  },
  {
    id: 23,
    name: "multishot",
    displayName: "Multishot",
    weight: 2,
    maxLevel: 1,
    description:
      "Shoots 3 arrows at once but only costs 1 arrow (from your inventory)",
    descriptionTW: "一次發射 3 箭，但只消耗 1 箭（來自你的背包）",
  },
  {
    id: 24,
    name: "piercing",
    displayName: "Piercing",
    weight: 10,
    maxLevel: 4,
    description: "Arrow can pierce through multiple entities",
    descriptionTW: "箭矢可以穿透多個實體",
  },
  {
    id: 25,
    name: "power",
    displayName: "Power",
    weight: 10,
    maxLevel: 5,
    description: "Increases damage dealt by bow",
    descriptionTW: "增加弓箭造成的傷害",
  },
  {
    id: 26,
    name: "projectile_protection",
    displayName: "Projectile Protection",
    weight: 5,
    maxLevel: 4,
    description: "Reduces projectile damage (arrows, fireballs, fire charges)",
    descriptionTW: "減少投射物傷害（箭矢、火球、火焰彈）",
  },
  {
    id: 27,
    name: "protection",
    displayName: "Protection",
    weight: 10,
    maxLevel: 4,
    description: "General protection against attacks, fire, lava, and falling",
    descriptionTW: "對攻擊、火焰、岩漿和墜落的總體保護",
  },
  {
    id: 28,
    name: "punch",
    displayName: "Punch",
    weight: 2,
    maxLevel: 2,
    description: "Increases knockback dealt (enemies repel backwards)",
    descriptionTW: "增加弓箭擊退效果（敵人向後推）",
  },
  {
    id: 29,
    name: "quick_charge",
    displayName: "Quick Charge",
    weight: 5,
    maxLevel: 3,
    description: "Reduces the amount of time to reload a crossbow",
    descriptionTW: "減少重新裝填弩的時間",
  },
  {
    id: 30,
    name: "respiration",
    displayName: "Respiration",
    weight: 2,
    maxLevel: 3,
    description: "Extends underwater breathing (see better underwater)",
    descriptionTW: "延長水下呼吸時間（在水下視野更清晰）",
  },
  {
    id: 31,
    name: "riptide",
    displayName: "Riptide",
    weight: 2,
    maxLevel: 3,
    description:
      "Propels the player forward when enchanted item is thrown while in water or rain",
    descriptionTW: "當附魔物品在水中或雨中被投擲時，將玩家向前旋轉推進",
  },
  {
    id: 32,
    name: "sharpness",
    displayName: "Sharpness",
    weight: 10,
    maxLevel: 5,
    description: "Increases attack damage dealt to mobs",
    descriptionTW: "增加對生物的攻擊傷害",
  },
  {
    id: 33,
    name: "silk_touch",
    displayName: "Silk Touch",
    weight: 1,
    maxLevel: 1,
    description: "Mines blocks themselves (fragile items)",
    descriptionTW: "挖掘方塊本身（易壞物品）",
  },
  {
    id: 34,
    name: "smite",
    displayName: "Smite",
    weight: 5,
    maxLevel: 5,
    description: "Increases attack damage against undead mobs",
    descriptionTW: "增加對不死生物的攻擊傷害",
  },
  {
    id: 35,
    name: "soul_speed",
    displayName: "Soul Speed",
    weight: 1,
    maxLevel: 3,
    description:
      "Speeds up how fast you can move across soul sand and soul soil",
    descriptionTW: "加快在靈魂沙和靈魂土上的移動速度",
  },
  {
    id: 36,
    name: "sweeping_edge",
    displayName: "Sweeping Edge",
    weight: 2,
    maxLevel: 3,
    description: "Increases damage of sweep attack",
    descriptionTW: "增加掃擊攻擊的傷害",
  },
  {
    id: 37,
    name: "swift_sneak",
    displayName: "Swift Sneak",
    weight: 1,
    maxLevel: 3,
    description: "Increases movement speed while sneaking",
    descriptionTW: "增加潛行時的移動速度",
  },
  {
    id: 38,
    name: "thorns",
    displayName: "Thorns",
    weight: 1,
    maxLevel: 3,
    description: "Causes damage to attackers",
    descriptionTW: "對攻擊者造成反擊傷害",
  },
  {
    id: 39,
    name: "unbreaking",
    displayName: "Unbreaking",
    weight: 5,
    maxLevel: 3,
    description:
      "Increases durability of item, in effect, by decreasing the chance of the tool, weapon, or armor taking durability damage when used",
    descriptionTW:
      "提高物品的耐久度，實際上是減少工具、武器或盔甲使用時受到耐久損壞的機率",
  },
  {
    id: 40,
    name: "vanishing_curse",
    displayName: "Curse of Vanishing",
    weight: 1,
    maxLevel: 1,
    description: "Cursed item will disappear after player dies",
    descriptionTW: "被詛咒的物品在玩家死亡後將消失",
  },
  {
    id: 41,
    name: "wind_burst",
    displayName: "Wind Burst",
    weight: 2,
    maxLevel: 1,
    description:
      "Emits a Wind Burst upon hitting an enemy (and attacker bounces upward)",
    descriptionTW: "擊中敵人時發出風暴（攻擊後會向上彈起）",
  },
];

module.exports = { ENCHANTMENTS };
