const FOODS = [
  { name: "rabbit_stew", hungerValue: 10, saturationValue: 12 },
  { name: "golden_carrot", hungerValue: 6, saturationValue: 14.4 },
  { name: "cooked_beef", hungerValue: 8, saturationValue: 12.8 },
  { name: "cooked_porkchop", hungerValue: 8, saturationValue: 12.8 },
  { name: "pumpkin_pie", hungerValue: 8, saturationValue: 4.8 },
  { name: "cooked_mutton", hungerValue: 6, saturationValue: 9.6 },
  { name: "cooked_salmon", hungerValue: 6, saturationValue: 9.6 },
  { name: "beetroot_soup", hungerValue: 6, saturationValue: 7.2 },
  { name: "cooked_chicken", hungerValue: 6, saturationValue: 7.2 },
  { name: "mushroom_stew", hungerValue: 6, saturationValue: 7.2 },
  { name: "suspicious_stew", hungerValue: 6, saturationValue: 7.2 },
  { name: "honey_bottle", hungerValue: 6, saturationValue: 1.2 },
  { name: "baked_potato", hungerValue: 5, saturationValue: 6 },
  { name: "bread", hungerValue: 5, saturationValue: 6 },
  { name: "cooked_cod", hungerValue: 5, saturationValue: 6 },
  { name: "cooked_rabbit", hungerValue: 5, saturationValue: 6 },
  { name: "enchanted_golden_apple", hungerValue: 4, saturationValue: 9.6 },
  { name: "golden_apple", hungerValue: 4, saturationValue: 9.6 },
  { name: "apple", hungerValue: 4, saturationValue: 2.4 },
  // { name: "chorus_fruit", hungerValue: 4, saturationValue: 2.4 },
  // { name: "rotten_flesh", hungerValue: 4, saturationValue: 0.8 },
  { name: "carrot", hungerValue: 3, saturationValue: 3.6 },
  { name: "beef", hungerValue: 3, saturationValue: 1.8 },
  { name: "porkchop", hungerValue: 3, saturationValue: 1.8 },
  { name: "rabbit", hungerValue: 3, saturationValue: 1.8 },
  // { name: "spider_eye", hungerValue: 2, saturationValue: 3.2 },
  { name: "chicken", hungerValue: 2, saturationValue: 1.2 },
  { name: "melon_slice", hungerValue: 2, saturationValue: 1.2 },
  { name: "mutton", hungerValue: 2, saturationValue: 1.2 },
  // { name: "poisonous_potato", hungerValue: 2, saturationValue: 1.2 },
  { name: "cod", hungerValue: 2, saturationValue: 0.4 },
  { name: "cookie", hungerValue: 2, saturationValue: 0.4 },
  { name: "glow_berries", hungerValue: 2, saturationValue: 0.4 },
  { name: "salmon", hungerValue: 2, saturationValue: 0.4 },
  { name: "sweet_berries", hungerValue: 2, saturationValue: 0.4 },
  { name: "beetroot", hungerValue: 1, saturationValue: 1.2 },
  { name: "dried_kelp", hungerValue: 1, saturationValue: 0.6 },
  { name: "potato", hungerValue: 1, saturationValue: 0.6 },
  // { name: "pufferfish", hungerValue: 1, saturationValue: 0.2 },
  { name: "tropical_fish", hungerValue: 1, saturationValue: 0.2 },
];

module.exports = { FOODS };
